blank_issues_enabled: false
contact_links:
  - name: ⚡ Discord
    url: https://discord.gg/Ntx2arK5WS
    about: If you have general questions or want to chat informally, join our Lab Automation Discord!
